version: '3.8'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app   
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/invoicedb

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: invoicedb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
