export const generateInvoiceList = (userId: number) => {
  return [
  {
    vendorName: 'Acme Corp',
    amount: 199.99,
    dueDate: new Date(),
    description: 'Consulting services for January',
    paid: false,
    userId: userId,
  },
  {
    vendorName: 'Globex',
    amount: 450,
    dueDate: new Date(),
    description: 'Software subscription - annual plan',
    paid: true,
    userId: userId,
  },
  {
    vendorName: 'Umbrella Corp',
    amount: 320.5,
    dueDate: new Date(),
    description: 'Lab equipment maintenance',
    paid: false,
    userId: userId,
  },
  {
    vendorName: 'Wayne Enterprises',
    amount: 890.0,
    dueDate: new Date(),
    description: 'Security system upgrade',
    paid: true,
    userId: userId,
  },
  {
    vendorName: 'Stark Industries',
    amount: 275.75,
    dueDate: new Date(),
    description: 'Prototype components',
    paid: false,
    userId: userId,
  },
  {
    vendorName: 'Oscorp',
    amount: 1100.0,
    dueDate: new Date(),
    description: 'R&D partnership fee',
    paid: true,
    userId: userId,
  },
  {
    vendorName: 'Hooli',
    amount: 620.45,
    dueDate: new Date(),
    description: 'Quarterly tech support',
    paid: false,
    userId: userId,
  },
  {
    vendorName: 'Wonka Industries',
    amount: 310.99,
    dueDate: new Date(),
    description: 'Product packaging',
    paid: false,
    userId: userId,
  },
  {
    vendorName: 'Initech',
    amount: 503.0,
    dueDate: new Date(),
    description: 'Software license renewal',
    paid: true,
    userId: userId,
  },
  {
    vendorName: 'Soylent Corp',
    amount: 200.0,
    dueDate: new Date(),
    description: 'Sustainability consulting',
    paid: false,
    userId: userId,
  }
]
}
